use std::collections::BTreeMap;

use crate::common::StoreKind;
use crate::error::PkgError;
use crate::refine::RefinedOutput;
use crate::walk::FileRecord;

/// One payload stripe generated from a refined record store.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Stripe {
    /// Snapshot-relative path.
    pub snap: String,
    /// Store represented by this stripe.
    pub store: StoreKind,
    /// Host file to read later when no buffer is embedded.
    pub file: Option<String>,
    /// Embedded bytes for records already read by the walker or generated by packing.
    pub buffer: Option<Vec<u8>>,
}

/// Packed records before executable prelude interpolation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PackedOutput {
    /// Refined entrypoint path.
    pub entrypoint: String,
    /// Refined symlink map.
    pub symlinks: BTreeMap<String, String>,
    /// Ordered payload stripes.
    pub stripes: Vec<Stripe>,
}

/// Convert refined records into payload stripes.
///
/// # Example
///
/// ```
/// let package = pkg_rust::PackageJson::parse("{}")
///     .map_err(|error| pkg_rust::PkgError::Resolve(error.to_string()))?;
/// let marker = pkg_rust::Marker::new(package);
/// let entrypoint = "../test/test-50-require-resolve/test-z-require-content.css";
/// let output = pkg_rust::walk(marker, entrypoint, None, pkg_rust::WalkerParams::new())?;
/// let refined = pkg_rust::refine_walked(output, entrypoint, pkg_rust::PathStyle::Posix);
/// let packed = pkg_rust::pack(refined, true)?;
/// assert!(!packed.stripes.is_empty());
/// # Ok::<(), pkg_rust::PkgError>(())
/// ```
pub fn pack(refined: RefinedOutput, bytecode: bool) -> Result<PackedOutput, PkgError> {
    let mut stripes = Vec::new();
    let symlinks = refined.symlinks;

    for (snap, mut record) in refined.records {
        if !has_any_store(&record) {
            continue;
        }
        if !record.stat {
            return Err(PkgError::Pack(format!("record '{snap}' has no stat store")));
        }

        if record.blob && !bytecode {
            record.blob = false;
            if !record.content {
                return Err(PkgError::Pack(format!(
                    "--no-bytecode requires source content for {}",
                    record.file.display()
                )));
            }
        }

        push_blob_or_content(&mut stripes, &snap, &record, StoreKind::Blob)?;
        push_blob_or_content(&mut stripes, &snap, &record, StoreKind::Content)?;
        push_links(&mut stripes, &snap, &record)?;
        push_stat(&mut stripes, &snap, &record)?;
    }

    Ok(PackedOutput {
        entrypoint: refined.entrypoint,
        symlinks,
        stripes,
    })
}

fn has_any_store(record: &FileRecord) -> bool {
    record.blob || record.content || record.links || record.stat
}

fn push_blob_or_content(
    stripes: &mut Vec<Stripe>,
    snap: &str,
    record: &FileRecord,
    store: StoreKind,
) -> Result<(), PkgError> {
    let enabled = match store {
        StoreKind::Blob => record.blob,
        StoreKind::Content => record.content,
        StoreKind::Links | StoreKind::Stat => false,
    };
    if !enabled {
        return Ok(());
    }

    let (file, buffer) = if let Some(body) = record.body.clone() {
        (None, Some(body))
    } else {
        (Some(record.file.display().to_string()), None)
    };

    stripes.push(Stripe {
        snap: snap.to_owned(),
        store,
        file,
        buffer,
    });
    Ok(())
}

fn push_links(stripes: &mut Vec<Stripe>, snap: &str, record: &FileRecord) -> Result<(), PkgError> {
    if !record.links {
        return Ok(());
    }

    let mut children = record.children.clone();
    children.sort();
    children.dedup();
    let buffer = serde_json::to_vec(&children)
        .map_err(|error| PkgError::Pack(format!("links json failed for '{snap}': {error}")))?;
    stripes.push(Stripe {
        snap: snap.to_owned(),
        store: StoreKind::Links,
        file: None,
        buffer: Some(buffer),
    });
    Ok(())
}

fn push_stat(stripes: &mut Vec<Stripe>, snap: &str, record: &FileRecord) -> Result<(), PkgError> {
    if !record.stat {
        return Ok(());
    }

    let Some(metadata) = record.metadata.as_ref() else {
        return Err(PkgError::Pack(format!(
            "record '{snap}' has stat store without metadata"
        )));
    };
    let buffer = serde_json::to_vec(metadata)
        .map_err(|error| PkgError::Pack(format!("stat json failed for '{snap}': {error}")))?;
    stripes.push(Stripe {
        snap: snap.to_owned(),
        store: StoreKind::Stat,
        file: None,
        buffer: Some(buffer),
    });
    Ok(())
}
